
---
title: "Lab 3A"
author: "Kate Newcomer"
date: "September 7, 2020"
output: html_document
---
```{r}
##wnload.file(url = "https://ndownloader.figshare.com/files/2292169",destfile = "data/portal_data_joined.csv")
```

```{r}
library(tidyverse)
```
```{r Loading_IndexingTheData}
surveys <- read.csv("data/portal_data_joined.csv")
head(surveys)
str(surveys)
# first element in the first column of the data frame (as a vector)
surveys[1, 1]   
# first element in the 6th column (as a vector)
surveys[1, 6]   
# first column of the data frame (as a vector)
surveys[, 1]    
# first column of the data frame (as a data.frame)
surveys[1]      
# first three elements in the 7th column (as a vector)
surveys[1:3, 7] 
# the 3rd row of the data frame (as a data.frame)
surveys[3, ]    
# equivalent to head_surveys <- head(surveys)
head_surveys <- surveys[1:6, ] 
surveys["species_id"]       # Result is a data.frame
surveys[, "species_id"]     # Result is a vector
surveys[["species_id"]]     # Result is a vector
surveys$species_id          # Result is a vector

```
              
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r Challenge1}
surveys_200 <- surveys[200, ]
n_rows <- nrow(surveys)
surveys_last <- surveys[n_rows, ]
surveys_middle <- surveys[n_rows / 2, ]
surveys_head <- surveys[-(7:n_rows), ]
```
```{r Factors}
sex <- factor(c("male", "female", "female", "male"))
levels(sex)
nlevels(sex)
sex
sex <- factor(sex, levels = c("male", "female"))
sex
```
```{r Converting_factors}
as.character(sex)
year_fct <- factor(c(1990, 1983, 1977, 1998, 1990))
as.numeric(year_fct)               
as.numeric(as.character(year_fct)) 
as.numeric(levels(year_fct))[year_fct] 
```
```{r renaming_factors}
plot(as.factor(surveys$sex))
sex <- factor(surveys$sex)
head(sex)
levels(sex)
levels(sex)[1]
levels(sex)
head(sex)
```

```{r Challenge}
levels(sex)[2:3] <- c("female", "male")
sex <- factor(sex, levels = c("female", "male", "undetermined"))
plot(sex)
```

```{r Using_stringsAsFactorsIsFalse}
surveys <- read.csv("data/portal_data_joined.csv", stringsAsFactors = TRUE)
str(surveys)
surveys <- read.csv("data/portal_data_joined.csv", stringsAsFactors = FALSE)
str(surveys)
## Convert the column "plot_type" into a factor
surveys$plot_type <- factor(surveys$plot_type)
```
```{r challenge}
animal_data <- data.frame(
          animal = c("dog", "cat", "sea cucumber", "sea urchin"),
          feel = c("furry","furry", "squishy","spiny"),
          weight = c(45, 8,1.1, 0.8)
          )

country_climate <- data.frame(
       country = c("Canada", "Panama", "South Africa", "Australia"),
       climate = c("cold", "hot", "temperate", "hot/temperate"),
       temperature = c(10, 30, 18, 15),
       northern_hemisphere = c(TRUE, TRUE, FALSE, FALSE),
       has_kangaroo = c(FALSE, FALSE, FALSE, TRUE)
       )


```
```{r formattingDates}
str(surveys)
library("lubridate")
my_date <- ymd("2020-09-07")
str(my_date)

my_date <- ymd(paste("2020","9","7", sep="-"))
str(my_date)

paste(surveys$year, surveys$month, surveys$day, sep = "-")

ymd(paste(surveys$year, surveys$month, surveys$day, sep = "-"))

surveys$date <- ymd(paste(surveys$year, surveys$month, surveys$day, sep = "-"))

str(surveys)

summary(surveys$date)

missing_dates <- surveys[is.na(surveys$date), c("year", "month", "day")]

head(missing_dates)

```





## R Markdown


