---
title: "lab5"
author: "Kate Newcomer"
date: "September 21, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
library(lubridate)
```

```{r}
Confirmed_State_3_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-13-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State") %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
```

```{r}
Confirmed_State_9_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv")) %>% 
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
```

# Exercise 2
```{r Exercise 2}
Confirmed_State_6_13 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/06-13-2020.csv")) %>%
  filter (Country_Region == "US") %>% 
  group_by(Province_State, Country_Region) %>% 
  summarise(Confirmed = sum(Confirmed)) 
  
Confirmed_State_6_13 <- Confirmed_State_6_13 %>% 
  filter(Province_State != "Recovered") 
Confirmed_State_6_13 <- Confirmed_State_6_13 %>% 
  filter(Province_State != "Recovered") 
Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State"))
head(Confirmed_State_6_13_9_13_joined)
```

```{r}
Confirmed_State_6_13_9_13_joined <- full_join(Confirmed_State_6_13,
      Confirmed_State_9_13, by = c("Province_State")) %>% 
      rename(Confirmed_6_13_2020 = "Confirmed.x", Confirmed_9_13_2020 = "Confirmed.y") %>% 
      select(-Country_Region.x, -Country_Region.y) %>% 
      replace_na(list(Confirmed_6_13_2020 = 0))
head(Confirmed_State_6_13_9_13_joined)
```
```{r}
Confirmed_State_6_13_9_13_joined_long <- Confirmed_State_6_13_9_13_joined %>% 
              pivot_longer(-c(Province_State),
                            names_to = "Date", values_to = "Confirmed")
```
```{r, fig.width = 40, fig.height = 40}
ggplot(Confirmed_State_6_13_9_13_joined, aes(x = Province_State,  y = Confirmed_6_13_2020))  + 
    geom_bar(stat='identity')
```
```{r}
time_series_confirmed <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")) %>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region")
head(time_series_confirmed)
```
```{r}
 download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv", 
               destfile = "data/time_series_covid19_deaths_global.csv")
time_series_deaths <- read_csv("data/time_series_covid19_deaths_global.csv")%>%
  rename(Province_State = "Province/State", Country_Region = "Country/Region") 
```
```{r}
time_series_deaths_long <- time_series_deaths %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Deaths") 
head(time_series_deaths_long)

```
```{r}
time_series_confirmed_long <- time_series_confirmed %>% 
               pivot_longer(-c(Province_State, Country_Region, Lat, Long),
                            names_to = "Date", values_to = "Confirmed") 

time_series_confirmed_long <- time_series_confirmed_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".", remove = FALSE)
head(time_series_confirmed_long)
```
```{r}
time_series_deaths_long <- time_series_deaths_long %>% 
  unite(Key, Province_State, Country_Region, Date, sep = ".") %>% 
  select(Key, Deaths)

time_series_long_joined <- full_join(time_series_confirmed_long,
              time_series_deaths_long, by = c("Key")) %>% 
  mutate("Deaths/Confirmed" = Deaths/Confirmed) %>%
              select(-Key) 
  
head(time_series_long_joined)
```
```{r}
time_series_long_joined$Date <- mdy(time_series_long_joined$Date)
time_series_long_joined_counts <- time_series_long_joined %>% 
  pivot_longer(-c(Province_State, Country_Region, Lat, Long, Date),
               names_to = "Report_Type", values_to = "Counts")
head(time_series_long_joined_counts)
```
# Exercise 4
```{r, fig.width = 20, fig.height = 10}
time_series_long_joined %>% 
    group_by(Date) %>% 
    summarise_at(c("Confirmed", "Deaths"), sum) %>% 
    
    ggplot(aes(x = Date,  y = Deaths)) + 
    geom_point() +
    geom_line() +
    ggtitle("COVID-19 Deaths")
```
# Exercise 5
```{r Exercise5}
time_series_long_joined_rate <- time_series_long_joined %>%
  filter(!is.na(Deaths), !is.na(Confirmed)) %>%
  mutate(deathrate = Deaths/Confirmed) %>%
  select(Deaths, Confirmed, deathrate)
  head(time_series_long_joined_rate)
```

# Exercise 6
```{r Exercise6}

  
time_series_long_joined %>% 
  group_by(Country_Region,Date) %>% 
  summarise_at(c("Confirmed", "Deaths"), sum) %>% 
  filter (Country_Region == "US") %>% 
    ggplot(aes(x = Date,  y = Deaths/Confirmed)) + 
    geom_point() +
    geom_line() +
    ggtitle("US COVID-19 Deaths")
```

# Exercise 7
```{r Exercise7}
top10C <- time_series_long_joined %>% 
  group_by(Country_Region) %>% 
  summarize(Total_Deaths = max(Deaths)) %>%
  arrange(desc(Total_Deaths)) %>%
  slice(1:10) 

time_series_long_joined %>%
  group_by(Date, Country_Region) %>%
  summarise_at(c("Deaths"), sum) %>%
  filter(Country_Region %in% top10C$Country_Region) %>% 
  ggplot(aes(x = Date, y=Deaths,color=Country_Region)) + 
    geom_point() +
    geom_line() +
    ggtitle("Top10 Deaths")
```

# Exercise 8
```{r Exercise8}
time_series_long_joined %>%
  group_by(Date, Country_Region) %>%
  summarise_at(c("Deaths"), sum) %>%
  filter(Country_Region %in% top10C$Country_Region) %>% 
  ggplot(aes(x = Date, y=Deaths,color=Country_Region)) + 
    geom_point() +
    geom_line() +
    facet_wrap(facets=vars(Country_Region))
```
```{r}
 download.file(url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv", 
               destfile = "data/time_series_covid19_deaths_US.csv")
time_series_USdeaths <- read_csv("data/time_series_covid19_deaths_US.csv")
```

# Exercise 9
```{r Exercise9}
time_US <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv")) %>% 
  filter (!Province_State %in% c("Alaska","Hawaii", "American Samoa",
                  "Puerto Rico","Northern Mariana Islands", 
                  "Virgin Islands", "Guam",
                  "District of Columbia")) %>%
    ggplot(aes(x = Date, y=Deaths,color=Country_Region)) + 
    geom_point() +
    geom_line() +
    facet_wrap(facets=vars(Country_Region))
  
```

```{r }
time_series_long_joined %>%
  group_by(Date, Country_Region) %>%
  summarise_at(c("Deaths"), sum) %>%
  filter(Country_Region %in% top10C$Country_Region) %>% 
  ggplot(aes(x = Date, y=Deaths,color=Country_Region)) + 
    geom_point() +
    geom_line() +
    facet_wrap(facets=vars(Country_Region)) + theme_bw()
```

# REFERENCES
[@Xie2020]
[@RCoreTeam]





